"""
build_previews.py  --  Pre-generate animated preview frames for the settings window.

Run whenever animals.py drawing code changes:
    python build_previews.py

Output: src/animal_previews.py  (8 walk-cycle frames per species, base64 PNG)

The settings window cycles through these frames using after() to animate
the critters in the Animals page cards.
"""

import base64
import io
import math
import os
import sys

# Headless pygame -- no window needed
os.environ.setdefault("SDL_VIDEODRIVER", "dummy")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "src"))

import pygame
pygame.display.init()
pygame.display.set_mode((1, 1))

from animals import Kitten, Turtle, Duck, Rabbit, Hedgehog, Squirrel, Otter, Panda

import PIL.Image

# Match the card background colour used in settings_window.py
_BG      = (30, 30, 53)
_SIZE    = 96     # preview canvas size (px)
_ANIMAL  = 62     # animal.size passed to constructor
_FRAMES  = 8      # walk-cycle frames

SPECIES = [
    ("kitten",   Kitten),
    ("turtle",   Turtle),
    ("duck",     Duck),
    ("rabbit",   Rabbit),
    ("hedgehog", Hedgehog),
    ("squirrel", Squirrel),
    ("otter",    Otter),
    ("panda",    Panda),
]


def _render_frame(cls, anim_t: float, walk_phase: float) -> bytes:
    surf = pygame.Surface((_SIZE, _SIZE))
    surf.fill(_BG)

    # Construct animal normally so all subclass attributes are set correctly.
    # Use a generous dummy screen so boundary logic never fires during draw.
    animal = cls(
        x=_SIZE / 2,
        y=_SIZE / 2 + 6,   # shift down a touch so ears clear the top edge
        size=_ANIMAL,
        screen_w=_SIZE * 4,
        screen_h=_SIZE * 4,
    )
    animal.direction   = 1          # always face right for consistency
    animal.anim_t      = anim_t
    animal.walk_phase  = walk_phase
    animal.state       = animal.WALKING
    animal.being_dragged = False
    animal.thrown        = False
    animal.spin_angle    = 0.0

    animal.draw(surf, anim_t)

    raw = pygame.image.tostring(surf, "RGB")
    img = PIL.Image.frombytes("RGB", (_SIZE, _SIZE), raw)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return buf.getvalue()


def _b64(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def main() -> None:
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "animal_previews.py")

    all_frames: dict[str, list[str]] = {}

    for species, cls in SPECIES:
        print(f"  {species:<14}", end="", flush=True)
        frames = []
        for i in range(_FRAMES):
            t = (i / _FRAMES) * 2 * math.pi
            png = _render_frame(cls, anim_t=t, walk_phase=t)
            frames.append(_b64(png))
            print(".", end="", flush=True)
        all_frames[species] = frames
        print(f"  {sum(len(f) for f in frames) // 1024} KB")

    # Write animal_previews.py
    lines = [
        '"""',
        "animal_previews.py -- Pre-generated animated preview frames for the settings window.",
        "",
        "Generated by build_previews.py -- do not edit by hand.",
        f"Frames per species: {_FRAMES}   Canvas: {_SIZE}x{_SIZE}px   Animal size: {_ANIMAL}",
        '"""',
        "",
        "# Single frame per species (frame 0) -- kept for backwards compatibility.",
        "PREVIEWS: dict[str, str] = {",
    ]
    for species, frames in all_frames.items():
        lines.append(f'    "{species}": "{frames[0]}",')
    lines.append("}")
    lines.append("")
    lines.append("# Full walk cycle -- 8 frames per species, used for animation in settings UI.")
    lines.append("FRAMES: dict[str, list[str]] = {")
    for species, frames in all_frames.items():
        lines.append(f'    "{species}": [')
        for f in frames:
            lines.append(f'        "{f}",')
        lines.append("    ],")
    lines.append("}")
    lines.append("")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))

    total_kb = sum(
        sum(len(f) for f in frames)
        for frames in all_frames.values()
    ) // 1024
    print(f"\nWrote {out}")
    print(f"{len(SPECIES)} species x {_FRAMES} frames  --  {total_kb} KB total (base64)")


if __name__ == "__main__":
    main()
